
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\xder>G\xe9\xa2IV\xbfk\xf3R"t\xb9\xeb'
    
_lr_action_items = {'SEPARATOR':([1,3,4,5,6,7,8,9,],[10,11,12,13,14,15,16,17,]),'$end':([2,22,32,37,44,45,50,51,52,54,55,56,59,63,],[0,-11,-12,-6,-3,-14,-7,-1,-2,-5,-13,-15,-4,-8,]),'SIZE':([18,],[29,]),'TARGET':([20,22,23,25,26,27,30,32,41,45,55,56,],[31,-11,36,38,39,40,43,-12,53,-14,-13,-15,]),'BOOLEAN':([62,],[64,]),'NONE':([21,],[33,]),'CSHAPEDORE':([0,],[1,]),'ITEMID':([13,21,48,],[24,34,57,]),'CSHAPELESSORE':([0,],[8,]),'COREDICT':([0,],[7,]),'AMOUNT':([34,35,],[46,47,]),'CFLUID':([0,],[4,]),'CITEM':([0,],[5,]),'CFURNACE':([0,],[6,]),'CSHAPELESS':([0,],[3,]),'RPAREN':([29,33,46,47,57,64,],[42,45,55,56,60,65,]),'ORENAME':([12,15,21,],[23,26,35,]),'ITEMDESCRIPTION':([24,61,65,],[37,63,-9,]),'CSHAPED':([0,],[9,]),'LPAREN':([10,11,14,16,17,19,20,22,27,28,30,31,32,36,38,39,40,41,42,43,45,49,51,53,55,56,58,60,],[18,21,21,21,18,21,21,-11,21,21,21,21,-12,48,21,21,21,21,-16,21,-14,48,21,21,-13,-15,62,-10,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ingredientlist':([11,16,19,28,39,],[20,27,30,41,51,]),'booleanst':([58,],[61,]),'fluid':([36,49,],[49,58,]),'main':([0,],[2,]),'ingredient':([11,14,16,19,20,27,28,30,31,38,39,40,41,43,51,53,],[22,25,22,22,32,32,22,32,44,50,22,52,32,54,32,59,]),'recipesize':([10,17,],[19,28,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> main","S'",1,None,None,None),
  ('main -> COREDICT SEPARATOR ORENAME TARGET ingredientlist','main',5,'p_main_modeoredict','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',12),
  ('main -> CSHAPELESSORE SEPARATOR ingredientlist TARGET ingredient','main',5,'p_main_modeshapeless','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',17),
  ('main -> CSHAPELESS SEPARATOR ingredientlist TARGET ingredient','main',5,'p_main_modeshapeless','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',18),
  ('main -> CSHAPED SEPARATOR recipesize ingredientlist TARGET ingredient','main',6,'p_main_modeshaped','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',23),
  ('main -> CSHAPEDORE SEPARATOR recipesize ingredientlist TARGET ingredient','main',6,'p_main_modeshaped','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',24),
  ('main -> CITEM SEPARATOR ITEMID ITEMDESCRIPTION','main',4,'p_main_modeitem','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',29),
  ('main -> CFURNACE SEPARATOR ingredient TARGET ingredient','main',5,'p_main_modefurnace','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',34),
  ('main -> CFLUID SEPARATOR ORENAME TARGET fluid fluid booleanst ITEMDESCRIPTION','main',8,'p_main_modeliquidreg','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',39),
  ('booleanst -> LPAREN BOOLEAN RPAREN','booleanst',3,'p_booleanst_st','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',45),
  ('fluid -> LPAREN ITEMID RPAREN','fluid',3,'p_fluid','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',50),
  ('ingredientlist -> ingredient','ingredientlist',1,'p_ingredientlist_single','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',55),
  ('ingredientlist -> ingredientlist ingredient','ingredientlist',2,'p_ingredientlist_multi','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',60),
  ('ingredient -> LPAREN ITEMID AMOUNT RPAREN','ingredient',4,'p_ingredient_item','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',71),
  ('ingredient -> LPAREN NONE RPAREN','ingredient',3,'p_ingredient_none','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',76),
  ('ingredient -> LPAREN ORENAME AMOUNT RPAREN','ingredient',4,'p_ingredient_orename','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',81),
  ('recipesize -> LPAREN SIZE RPAREN','recipesize',3,'p_recipesize','D:\\MyDocs\\lang\\python\\recipeparser\\repmak_yacc.py',86),
]
